version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "civic-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-er495j0xptsj"
s3_prefix = "civic-stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
